name: mcp_dart
description: MCP SDK for Dart
version: 0.0.1
repository: https://github.com/leehack/mcp_dart

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
